version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: askme
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    container_name: pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres


  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8090:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  postgres:
  pgadmin:

