# Generated by Django 5.1.2 on 2024-11-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme_nagapetyan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='answerlike',
            table='answer_like',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='questionlike',
            table='question_like',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
