# Generated by Django 5.1.2 on 2024-11-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_nagapetyan', '0002_alter_answer_table_alter_answerlike_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
